#!/bin/bash
# =============================================================
# TIrtayana OpenWrt - Local Packaging Script for B860H (S905X)
# Uses ophub/amlogic-s9xxx-openwrt to repack rootfs with
# a custom kernel for the STB B860H (Amlogic S905X)
# =============================================================
# Usage:
#   chmod +x scripts/pack-b860h.sh
#   sudo ./scripts/pack-b860h.sh
#   sudo ./scripts/pack-b860h.sh -k 6.6.y
#   sudo ./scripts/pack-b860h.sh -k 6.1.y -s 2048 -i 192.168.2.1
# =============================================================

set -euo pipefail

# ── Terminal colors ──────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# ── Default configuration ─────────────────────────────────────
BOARD="s905x"                          # Chip B860H = Amlogic S905X
KERNEL_VERSION="6.1.y_6.6.y"          # Multiple kernel series
OPENWRT_IP="192.168.1.1"              # Default router IP
ROOTFS_SIZE="256/1024"                 # BOOTFS/ROOTFS in MB
BUILDER_NAME="TIrtayana"
OPHUB_REPO="https://github.com/ophub/amlogic-s9xxx-openwrt.git"
OPHUB_DIR="/tmp/ophub-packager"
ROOTFS_PATTERN="bin/targets/armsr/armv8/*rootfs.tar.gz"
OUTPUT_DIR="out/b860h"
KERNEL_REPO=""
PROFILE=""
COMPILE_FIRST="false"

# ── Helper functions ────────────────────────────────────────
info()    { echo -e "${CYAN}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC}   $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERR]${NC}  $*"; exit 1; }
header()  { echo -e "\n${BOLD}${BLUE}════════════════════════════════════════${NC}"; \
            echo -e "${BOLD}${BLUE}  $*${NC}"; \
            echo -e "${BOLD}${BLUE}════════════════════════════════════════${NC}"; }

# ── Banner ──────────────────────────────────────────────────
print_banner() {
    echo -e "${CYAN}"
    cat << 'EOF'
 ████████╗██╗██████╗ ████████╗ █████╗ ██╗   ██╗ █████╗ ███╗   ██╗ █████╗
 ╚══██╔══╝██║██╔══██╗╚══██╔══╝██╔══██╗╚██╗ ██╔╝██╔══██╗████╗  ██║██╔══██╗
    ██║   ██║██████╔╝   ██║   ███████║ ╚████╔╝ ███████║██╔██╗ ██║███████║
    ██║   ██║██╔══██╗   ██║   ██╔══██║  ╚██╔╝  ██╔══██║██║╚██╗██║██╔══██║
    ██║   ██║██║  ██║   ██║   ██║  ██║   ██║   ██║  ██║██║ ╚████║██║  ██║
    ╚═╝   ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝
EOF
    echo -e "${NC}"
    echo -e "  ${BOLD}OpenWrt Packaging Script for STB B860H (Amlogic S905X)${NC}"
    echo -e "  ${YELLOW}Powered by ophub/amlogic-s9xxx-openwrt${NC}"
    echo ""
}

# ── Argument parsing ─────────────────────────────────────────
usage() {
    echo -e "Usage: ${BOLD}$0 [options]${NC}"
    echo ""
    echo "  -k  Kernel version   (default: ${KERNEL_VERSION})"
    echo "      Example: -k 6.6.y  or  -k 6.1.y_6.6.y"
    echo "  -i  IP Address       (default: ${OPENWRT_IP})"
    echo "  -s  Rootfs size      (default: ${ROOTFS_SIZE} = BOOT/ROOT in MB)"
    echo "  -b  Target board     (default: ${BOARD})"
    echo "  -n  Builder name     (default: ${BUILDER_NAME})"
    echo "  -o  Output dir       (default: ${OUTPUT_DIR})"
    echo "  -r  Custom Ophub     (default: ${OPHUB_REPO})"
    echo "  -R  Custom Kernel    (default: optional)"
    echo "  -p  Build profile    (default: optional)"
    echo "  -c  Recompile OpenWrt from scratch before packaging"
    echo "  -h  Display this help message"
    echo ""
    echo "Examples:"
    echo "  sudo $0 -c -k 6.6.y"
    echo "  sudo $0 -k 6.1.y -i 10.0.0.1"
    exit 0
}

while getopts "k:i:s:b:n:o:r:R:p:hc" opt; do
    case "$opt" in
        k) KERNEL_VERSION="$OPTARG" ;;
        i) OPENWRT_IP="$OPTARG" ;;
        s) ROOTFS_SIZE="$OPTARG" ;;
        b) BOARD="$OPTARG" ;;
        n) BUILDER_NAME="$OPTARG" ;;
        o) OUTPUT_DIR="$OPTARG" ;;
        r) OPHUB_REPO="$OPTARG" ;;
        R) KERNEL_REPO="$OPTARG" ;;
        p) PROFILE="$OPTARG" ;;
        h) usage ;;
        c) COMPILE_FIRST="true" ;;
        *) usage ;;
    esac
done

# ── Root check check ─────────────────────────────────────────
check_root() {
    if [ "$(id -u)" -ne 0 ]; then
        error "This script must be run as root.\n  Use: sudo $0 $*"
    fi
}

# ── Optional Recompile ────────────────────────────────────────
rebuild_openwrt() {
    if [ "${COMPILE_FIRST}" == "true" ]; then
        header "Rebuilding OpenWrt from Scratch"
        
        # OpenWrt forbids compiling as root. Since this script is run via sudo,
        # we must drop privileges back to the original user for the compilation step.
        local orig_user="${SUDO_USER:-}"
        
        if [ -z "${orig_user}" ] || [ "${orig_user}" == "root" ]; then
            warn "Running directly as root or SUDO_USER not detected."
            warn "OpenWrt compilation might fail if you are actually root."
            orig_user="${USER}"
        fi
        
        # Repair ownership: files generated by previous root processes must be owned by the user
        info "Repairing file ownerships before compiling..."
        chown -R "${orig_user}:${orig_user}" .
        
        # Cleanup broken build folders (common cause of patch failures)
        if [ -d "build_dir" ]; then
            info "Cleaning up potentially broken build directories..."
            rm -rf build_dir/toolchain-*/*/gcc-* 2>/dev/null || true
        fi
        
        info "Preparing configuration for profile: ${PROFILE:-standard}..."
        
        # Load profile-specific config if it exists
        if [ -n "${PROFILE}" ] && [ -f ".config.${PROFILE}" ]; then
            cp ".config.${PROFILE}" .config
            info "Loaded .config.${PROFILE}"
        elif [ ! -f ".config" ]; then
            warn "No .config found, using default standard config"
            [ -f ".config.standard" ] && cp ".config.standard" .config
        fi

        # Enforce architecture targets (same as GitHub Actions)
        # We use a temp file to avoid issues with sed/redirection during privilege drop
        cat > .config.extra <<EOF
CONFIG_TARGET_armsr=y
CONFIG_TARGET_armsr_armv8=y
CONFIG_TARGET_armsr_armv8_DEVICE_generic=y
CONFIG_TARGET_ROOTFS_TARGZ=y
EOF
        cat .config.extra >> .config
        rm .config.extra
        
        # Sync with GitHub Actions: Fix Kernel Config Conflicts
        info "Resolving potential kernel config conflicts..."
        local conflict_opts=("CONFIG_ARM64_VA_BITS_48" "CONFIG_IOMMU_DEFAULT_PASSTHROUGH" "CONFIG_NO_HZ_IDLE")
        for opt in "${conflict_opts[@]}"; do
            sed -i "/^${opt}=/d" .config 2>/dev/null || true
            sed -i "/^# ${opt} /d" .config 2>/dev/null || true
        done
        
        chown "${orig_user}:${orig_user}" .config

        # ── Clean stale package install artifacts ────────────────────────
        # When recompiling after a previous build used a different kernel version,
        # the old kmod package stamps cause "kernel hash mismatch" errors.
        # Root cause: bin/targets/.../packages/ contains old kmod-*.ipk files
        # baked against the old kernel hash. The package index then lists these
        # stale packages and make package/install picks them instead of the new ones.
        info "Cleaning stale package install stamps + kmod artifacts (kernel hash reset)..."

        # 1. Remove staging rootfs and package install stamp
        rm -f  staging_dir/target-*/stamp/.package_install 2>/dev/null || true
        rm -rf staging_dir/target-*/root-* 2>/dev/null || true
        rm -f  staging_dir/target-*/pkginfo/*.control 2>/dev/null || true
        rm -f  staging_dir/target-*/stamp/.target_compile 2>/dev/null || true

        # 2. THE ACTUAL FIX: delete stale kmod .ipk files from bin/ output dir
        #    These get built against old kernel hash and persist between runs.
        find bin/ -name "kmod-*.ipk" -delete 2>/dev/null || true
        # Also delete the package Packages index so it gets regenerated cleanly
        find bin/ -name "Packages" -delete 2>/dev/null || true
        find bin/ -name "Packages.gz" -delete 2>/dev/null || true
        find bin/ -name "Packages.manifest" -delete 2>/dev/null || true

        success "Stale kmod packages and index cleaned — kernel will be rebuilt cleanly"
        # ────────────────────────────────────────────────────────────────

        info "Running make defconfig && make -j$(nproc)..."
        
        # Execute compilation in the current directory as the normal user
        # We use 'sudo -u' instead of 'su' for better compatibility with sudo environments
        # make olddefconfig ensures no interactive prompts for new symbols
        yes "" | sudo -u "${orig_user}" make defconfig || true
        yes "" | sudo -u "${orig_user}" make olddefconfig || true
        sudo -u "${orig_user}" make -j$(nproc) || sudo -u "${orig_user}" make -j1 V=s || error "OpenWrt compilation failed!"

        success "OpenWrt compilation finished!"
    fi
}

# ── Check dependencies ────────────────────────────────────────
check_deps() {
    header "Checking Dependencies"
    local deps=(git curl wget tar gzip)
    local missing=()

    for dep in "${deps[@]}"; do
        if command -v "$dep" &>/dev/null; then
            success "$dep is available"
        else
            missing+=("$dep")
            warn "$dep is missing"
        fi
    done

    if [ ${#missing[@]} -gt 0 ]; then
        info "Installing missing dependencies: ${missing[*]}"
        apt-get update -y -qq
        apt-get install -y -qq "${missing[@]}"
        success "Dependencies installed successfully"
    fi
}

# ── Find rootfs file ──────────────────────────────────────────
find_rootfs() {
    header "Searching for rootfs.tar.gz file"

    # Search in build output directory
    ROOTFS_FILE=$(ls ${ROOTFS_PATTERN} 2>/dev/null | tail -1)


    if [ -z "${ROOTFS_FILE}" ]; then
        echo ""
        warn "Rootfs file not found at: ${ROOTFS_PATTERN}"
        echo ""
        echo -e "  ${YELLOW}Make sure to build OpenWrt first:${NC}"
        echo -e "  ${BOLD}  make -j\$(nproc) || make -j1 V=s${NC}"
        echo ""
        echo -e "  ${YELLOW}Required file:${NC}"
        echo -e "  ${BOLD}  bin/targets/armsr/armv8/*-rootfs.tar.gz${NC}"
        echo ""
        error "Build OpenWrt first, then run this script again."
    fi

    success "Found: ${ROOTFS_FILE}"
    info "Size: $(du -sh "${ROOTFS_FILE}" | cut -f1)"
}

# ── Clone or update ophub ─────────────────────────────────────
setup_ophub() {
    header "Preparing Ophub Packager"

    if [ -d "${OPHUB_DIR}" ]; then
        info "Ophub directory exists, updating..."
        git -C "${OPHUB_DIR}" pull --ff-only origin main || {
            warn "Git pull failed, removing and cloning again..."
            rm -rf "${OPHUB_DIR}"
        }
    fi

    if [ ! -d "${OPHUB_DIR}" ]; then
        info "Cloning ophub/amlogic-s9xxx-openwrt..."
        git clone --depth=1 "${OPHUB_REPO}" "${OPHUB_DIR}"
    fi

    success "Ophub packager is ready at: ${OPHUB_DIR}"
}

# ── Prepare workspace ─────────────────────────────────────────
prepare_workspace() {
    header "Preparing Workspace"

    # Create openwrt-armsr folder required by ophub
    local armsr_dir="${OPHUB_DIR}/openwrt-armsr"
    rm -rf "${armsr_dir}"
    mkdir -p "${armsr_dir}"

    # Copy rootfs there
    info "Copying rootfs to ophub workspace..."
    cp "${ROOTFS_FILE}" "${armsr_dir}/"
    success "Rootfs copied to: ${armsr_dir}/"

    # Create local output dir
    mkdir -p "${OUTPUT_DIR}"
}

# ── Execute packaging ─────────────────────────────────────────
run_packaging() {
    header "Packaging Firmware for B860H"

    echo ""
    echo -e "  ${BOLD}Packaging configuration:${NC}"
    echo -e "  ├─ Board        : ${CYAN}${BOARD}${NC} (Amlogic S905X = B860H)"
    echo -e "  ├─ Kernel       : ${CYAN}${KERNEL_VERSION}${NC}"
    echo -e "  ├─ Default IP   : ${CYAN}${OPENWRT_IP}${NC}"
    echo -e "  ├─ Partitions   : ${CYAN}${ROOTFS_SIZE}${NC} MB (BOOT/ROOT)"
    echo -e "  ├─ Builder      : ${CYAN}${BUILDER_NAME}${NC}"
    if [ -n "${PROFILE}" ]; then
        echo -e "  ├─ Profile      : ${CYAN}${PROFILE}${NC}"
    fi
    if [ -n "${KERNEL_REPO}" ]; then
        echo -e "  ├─ Kernel Repo  : ${CYAN}${KERNEL_REPO}${NC}"
    fi
    echo -e "  └─ rootfs       : ${CYAN}${ROOTFS_FILE}${NC}"
    echo ""

    cd "${OPHUB_DIR}"

    local final_builder="${BUILDER_NAME}"
    if [ -n "${PROFILE}" ]; then
        final_builder="${BUILDER_NAME}_${PROFILE}"
    fi

    if [ -n "${KERNEL_REPO}" ]; then
        export CUSTOM_KERNEL_REPO="${KERNEL_REPO}"
    fi

    # Run ophub remake script
    sudo -E ./remake \
        -b "${BOARD}" \
        -k "${KERNEL_VERSION}" \
        -p "${OPENWRT_IP}" \
        -s "${ROOTFS_SIZE}" \
        -n "${final_builder}" \
        -a true

    cd - > /dev/null
    success "Packaging process completed!"
}

# ── Copy results to output dir ────────────────────────────────
collect_output() {
    header "Collecting Firmware Results"

    local ophub_out="${OPHUB_DIR}/openwrt/out"

    if [ ! -d "${ophub_out}" ] || [ -z "$(ls -A "${ophub_out}" 2>/dev/null)" ]; then
        error "No output found in: ${ophub_out}"
    fi

    local DATE_TAG
    DATE_TAG=$(date +%Y.%m.%d)

    local PROFILE_TAG="${PROFILE:-standard}"
    # Sanitize kernel version for filename: 6.1.y → 6.1, 6.1.167 → 6.1.167
    local KERNEL_TAG
    KERNEL_TAG=$(echo "${KERNEL_VERSION}" | sed 's/\.y//' | cut -d_ -f1)

    # Copy and rename: openwrt_amlogic_* → TIrtayana-B860H-{profile}-k{kernel}-{date}.img.gz
    for f in "${ophub_out}/"*.img.gz "${ophub_out}/"*.img; do
        [ -f "$f" ] || continue
        local EXT="${f##*.}"
        # Preserve the inner extension (.img.gz vs .img)
        if [[ "$f" == *.img.gz ]]; then
            local TARGET="${OUTPUT_DIR}/TIrtayana-B860H-${PROFILE_TAG}-k${KERNEL_TAG}-${DATE_TAG}.img.gz"
        else
            local TARGET="${OUTPUT_DIR}/TIrtayana-B860H-${PROFILE_TAG}-k${KERNEL_TAG}-${DATE_TAG}.img"
        fi
        cp -v "$f" "$TARGET"
    done

    echo ""
    success "Firmware is available in: ${OUTPUT_DIR}/"
    echo ""
    echo -e "  ${BOLD}Generated files:${NC}"
    ls -lh "${OUTPUT_DIR}/" | grep -v "^total" | while read -r line; do
        echo -e "  ${GREEN}✔${NC} $line"
    done
}

# ── Installation instructions ─────────────────────────────────
print_install_guide() {
    header "Installation Guide for STB B860H"

    echo -e "  ${BOLD}1. Flash to USB/SD Card${NC}"
    echo -e "     Use ${YELLOW}Rufus${NC} or ${YELLOW}balenaEtcher${NC}:"
    echo -e "     File: ${CYAN}${OUTPUT_DIR}/*.img.gz${NC}"
    echo ""
    echo -e "  ${BOLD}2. Boot from USB/SD${NC}"
    echo -e "     Plug into STB B860H, turn on → automatic boot"
    echo ""
    echo -e "  ${BOLD}3. Access LuCI${NC}"
    echo -e "     Open browser → ${CYAN}http://${OPENWRT_IP}${NC}"
    echo -e "     User: ${YELLOW}root${NC} | Pass: ${YELLOW}TIudayana${NC}"
    echo ""
    echo -e "  ${BOLD}4. Install to eMMC (Optional)${NC}"
    echo -e "     System → ${YELLOW}TIrtayana Service${NC} → ${YELLOW}Install OpenWrt${NC}"
    echo -e "     Select board: ${CYAN}B860H${NC} → click Install"
    echo ""
    echo -e "  ${BOLD}5. Backup Android ROM (Before installing to eMMC)${NC}"
    echo -e "     System → ${YELLOW}TIrtayana Service${NC} → ${YELLOW}Backup / Restore ROM${NC}"
    echo ""
    echo -e "  ${BOLD}LuCI Theme:${NC} ${CYAN}Argon Tirtayana (Custom Gold Theme)${NC}"
    echo -e "  Theme config: System → ${YELLOW}Argon Config${NC}"
    echo ""
}

# ── Main ──────────────────────────────────────────────────────
main() {
    print_banner
    check_root "$@"
    check_deps
    rebuild_openwrt
    find_rootfs
    setup_ophub
    prepare_workspace
    run_packaging
    collect_output
    print_install_guide

    echo -e "${GREEN}${BOLD}✅  All done! The B860H Firmware is ready to use.${NC}"
    echo ""
}

main "$@"
